"""Demo deliverables: the outputs a viewer must SEE or HEAR, planned by the planner, generated in the background.

Flow: the planner lists deliverables in its design and engine/manifest.py validates them. After the build,
start() runs a background job: the media director (reasoning tier) writes a prompt and a script for every variant,
then every asset is generated by the newest verified model of its tier through the Troubleshooter (retries,
fallback models). Images come first, so a video can start from an image (one avatar across all languages).

Clip checker: when settings.media_qa is on, a reasoning-tier model watches or listens to every generated file and
reads every generated text (engine/media_qa.py). A failed check regenerates the asset with the findings as a hint,
then checks again; the best-scoring result is kept, so the UI can warn. A checker outage never fails an asset.
A clip or image the checker found off-brief (it shows something other than what the brief asks for, typically the
story's hero instead of the product) is not regenerated from the same prompt: the director writes the prompt again
with the finding, then it is made again.
A chat deliverable's file is the assistant's first reply: the first turn (the director's system instruction with
its Context section, the first user message) is played at build time, the transcript is checked, and a failed
check plays it again with the findings, like any other output. redirect() has the director write the setup of a
project's chats again and replays them (used for chats directed before the assistant got its context). When a
deliverable plays a story scene, a soft "plays_scene" check
reports outputs that drift off the scene without failing them. quality_summary() / quality_row() roll the
verdicts up into one scorecard row.

Video length: the planner states a video's "seconds" (from the title or brief, snapped to an even 4-32 s). Veo
films one shot of 4, 6 or 8 s, so a longer video is filmed as consecutive shots (engine/manifest.shot_lengths),
the director writing one prompt and script per shot; every shot starts from the last frame of the one before
(image-to-video) so the story is continuous, and ffmpeg joins them into one file (_film). The clip's real length is
read from the file (length_s) and a soft "length" check reports a clip shorter or longer than planned.

Data outputs: a "structured" result or an "agent_trace" run is generated as JSON on a text tier (JSON mode),
validated strictly by manifest.parse_output() (a broken answer is an OutputError, so the Troubleshooter re-prompts
with the reason) and saved as .json. Its programmatic schema check runs before the checker model; a failure
regenerates it like any failed critical check.

Check telemetry: every pass/fail verdict (not skipped) is reported to the resolver as record_check(tier of the
generating model, the model that generated the asset, passed), when the resolver offers that method.

Incremental rebuild: every deliverable and variant carries a spec hash. When start() gets a new manifest (a new
build or an edit), variants whose spec is unchanged and whose file from the previous status is still on disk
are carried over; only new or changed ones are directed and generated. A video counts as changed when the
image it starts from is regenerated.

The UI renders whatever the status file lists (deliverables/status.json), so a new kind of request needs no UI
change: the manifest drives the tabs. There are no canned assets, keywords or per-customer rules.
"""
import contextlib
import hashlib
import json
import logging
import os
import secrets
import tempfile
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from typing import Callable, Dict, List, Optional, Tuple

from engine import brain, manifest, media, media_qa, modality_eval, vertex
from engine.common import file_lock, iso, read_json, redact, slugify, write_json
from engine.config import Settings
from engine.mcp_knowledge_client import McpKnowledgeClient
from engine.model_resolver import ROLES, ModelResolver
from engine.troubleshooter import OutputError, StepFailed, Troubleshooter

logger = logging.getLogger(__name__)

EXT = {"video/mp4": ".mp4", "image/png": ".png", "image/jpeg": ".jpg", "image/webp": ".webp", "audio/wav": ".wav",
       "audio/mpeg": ".mp3", "audio/mp3": ".mp3", "text/markdown": ".md", "application/json": ".json"}
MEDIA_EXTS = frozenset(EXT.values()) | {".bin"}
STATUS_FILE = "status.json"
FOLDER = "deliverables"
SPEC_KEYS = ("kind", "title", "brief", "tier", "model", "start_from")
STORY_KEYS = ("beat", "scene")  # hashed only when set, so builds made before stories keep their clips
LENGTH_KEYS = ("seconds", "input_of")  # likewise: a video length other than the default, an input example's target
CARRY_KEYS = ("prompt", "script", "shots", "file", "mime", "model", "seconds", "length_s", "note", "qa", "metrics")
QUALITY_METRIC = "Demo output quality"
MAX_QUALITY_LABELS = 5  # labels listed per problem in the scorecard notes; the rest are counted

_JOBS: Dict[str, threading.Thread] = {}
_JOBS_LOCK = threading.Lock()


class _Superseded(Exception):
    """A newer build (or edit) replaced this project folder's status; the job stops without touching it."""


RETRY_DELAYS_S = (20, 60, 120)  # pause before each automatic round for failed assets (transient outages pass)


def _pause(stop: threading.Event, seconds: int) -> bool:
    """Wait up to `seconds`, one second at a time. -> True if the job was superseded meanwhile."""
    for _ in range(int(seconds)):
        if stop.is_set():
            return True
        time.sleep(1)
    return stop.is_set()


# ---------------------------------------------------------------------------------------------- status file
def folder(project_dir: str) -> str:
    return os.path.join(project_dir, FOLDER)


def status_path(project_dir: str) -> str:
    return os.path.join(folder(project_dir), STATUS_FILE)


def load_status(project_dir: str) -> Optional[dict]:
    state = read_json(status_path(project_dir), None)
    return state if isinstance(state, dict) and isinstance(state.get("deliverables"), list) else None


def asset_path(project_dir: str, asset: dict) -> str:
    """Absolute path of a generated file, '' if missing. The name must be a plain file name in the folder."""
    name = str(asset.get("file") or "")
    if not name or os.path.basename(name) != name or name.startswith(".") or name == STATUS_FILE:
        return ""
    path = os.path.join(folder(project_dir), name)
    return path if os.path.isfile(path) else ""


def counts(state: Optional[dict]) -> Dict[str, int]:
    """Asset counts by status (chat and unsupported assets included). "checking" assets (the clip checker is
    reviewing them) also count as "running", so running + pending + ready + failed + unsupported = total."""
    out = {"total": 0, "ready": 0, "failed": 0, "running": 0, "pending": 0, "unsupported": 0, "checking": 0}
    for d in (state or {}).get("deliverables", []):
        for a in d.get("assets", []):
            out["total"] += 1
            status = a.get("status", "pending")
            if status == "checking":
                out["checking"] += 1
                status = "running"
            out[status] = out.get(status, 0) + 1
    return out


# ---------------------------------------------------------------------------------------------- scorecard
def _quality_label(d: dict, a: dict) -> str:
    title = d.get("title") or d.get("id") or "Output"
    return " ".join(f"{title} / {a.get('label') or ''}".split())[:120]


def quality_summary(state: Optional[dict]) -> dict:
    """How the generated outputs fared with the clip checker. Unsupported assets are left out.
    -> {total: ready or failed assets, checked: assets with a pass/fail verdict, passed: verdict pass,
        warned: ['Title / Variant' with verdict fail], failed: [labels that could not be generated],
        pending: assets not finished (pending, running, checking), skipped: finished assets not checked,
        off_scene: [labels whose soft story-scene check failed],
        wrong_length: [labels of videos that do not run the planned length (soft length check failed)]}"""
    out = {"total": 0, "checked": 0, "passed": 0, "warned": [], "failed": [], "pending": 0, "skipped": 0,
           "off_scene": [], "wrong_length": []}
    for d in (state or {}).get("deliverables") or []:
        if not isinstance(d, dict):
            continue
        for a in d.get("assets") or []:
            if not isinstance(a, dict):
                continue
            status = a.get("status", "pending")
            if status == "unsupported":
                continue
            if status not in ("ready", "failed"):
                out["pending"] += 1
                continue
            out["total"] += 1
            label = _quality_label(d, a)
            if status == "failed":
                out["failed"].append(label)
                continue
            qa = a.get("qa") if isinstance(a.get("qa"), dict) else {}
            verdict = qa.get("verdict")
            if verdict in ("pass", "fail"):
                out["checked"] += 1
                if verdict == "pass":
                    out["passed"] += 1
                else:
                    out["warned"].append(label)
            else:
                out["skipped"] += 1
            if media_qa.off_scene(qa):
                out["off_scene"].append(label)
            if media_qa.wrong_length(qa):
                out["wrong_length"].append(label)
    return out


def _labels(labels: List[str]) -> str:
    shown = ", ".join(labels[:MAX_QUALITY_LABELS])
    more = len(labels) - MAX_QUALITY_LABELS
    return shown + (f" (+{more} more)" if more > 0 else "")


def quality_row(state: Optional[dict]) -> Optional[dict]:
    """The scorecard row for the demo outputs, shaped like the use-case synthesizer's rubric rows. None when there
    is no status, no deliverables, or nothing that can be generated (every asset unsupported). Off-scene outputs
    are listed in the notes but do not fail the row: the scene check is soft."""
    if not isinstance(state, dict) or not state.get("deliverables"):
        return None
    q = quality_summary(state)
    if not q["total"] and not q["pending"]:
        return None
    notes = []
    if q["failed"]:
        notes.append(f"not generated: {_labels(q['failed'])}")
    if q["warned"]:
        notes.append(f"failed a critical check: {_labels(q['warned'])}")
    if q["off_scene"]:
        notes.append(f"off-scene: {_labels(q['off_scene'])}")
    if q["wrong_length"]:
        notes.append(f"not the planned length: {_labels(q['wrong_length'])}")
    if q["skipped"]:
        notes.append(f"{q['skipped']} not checked")
    if q["pending"]:
        notes.append(f"{q['pending']} still generating or being checked")
    value = f"{q['passed']}/{q['total']} passed" + (f" · {q['pending']} pending" if q["pending"] else "")
    return {"metric": QUALITY_METRIC, "value": value, "threshold": "every output passes its critical checks",
            "notes": "; ".join(notes) or "all outputs passed their checks", "method": "clip checker",
            "pass": q["pending"] == 0 and not q["warned"] and not q["failed"] and q["total"] > 0}


def is_running(project_dir: str) -> bool:
    with _JOBS_LOCK:
        t = _JOBS.get(os.path.abspath(status_path(project_dir)))
        return bool(t and t.is_alive())


# ---------------------------------------------------------------------------------------------- spec hashes
def _digest(obj) -> str:
    return hashlib.sha256(json.dumps(obj, sort_keys=True, ensure_ascii=False).encode("utf-8")).hexdigest()[:16]


def _variant_key(v: dict) -> dict:
    return {"label": str(v.get("label") or ""), "language": str(v.get("language") or "")}


def _base_spec(d: dict, by_id: Dict[str, dict]) -> dict:
    base = {k: str(d.get(k) or "") for k in SPEC_KEYS}
    base.update({k: str(d[k]) for k in STORY_KEYS if d.get(k)})
    if d.get("kind") == "video" and d.get("seconds") and int(d["seconds"]) != manifest.DEFAULT_VIDEO_S:
        base["seconds"] = str(int(d["seconds"]))
    if d.get("input_of"):
        base["input_of"] = str(d["input_of"])
    src = by_id.get(d.get("start_from") or "") if d.get("kind") == "video" else None
    if src:  # a video starts from the first variant of its image: that image's spec is part of the video's
        base["start_image"] = _digest({**{k: str(src.get(k) or "") for k in SPEC_KEYS},
                                       **_variant_key((src.get("variants") or [{}])[0])})
    return base


def spec_hashes(deliverables: List[dict]) -> Dict[str, dict]:
    """{deliverable id: {"spec_hash": ..., "variants": {label: variant hash}}} for a validated manifest. The
    deliverable hash covers kind, title, brief, tier, model, start_from (and that image's spec), a video length
    other than the default, an input example's target and every variant; a variant hash covers the same fields
    for that one variant."""
    by_id = {d.get("id"): d for d in deliverables}
    out: Dict[str, dict] = {}
    for d in deliverables:
        base = _base_spec(d, by_id)
        variants = [_variant_key(v) for v in d.get("variants", [])]
        out[d.get("id")] = {"spec_hash": _digest({**base, "variants": variants}),
                            "variants": {v["label"]: _digest({**base, **v}) for v in variants}}
    return out


def _spec_changed(state: dict, deliverables: List[dict]) -> bool:
    """True if a manifest differs from the one the status was built from. A status written before spec hashes
    existed is treated as unchanged, so resuming an old build never regenerates its media."""
    if any("spec_hash" not in d for d in state["deliverables"]):
        return False
    new = spec_hashes(deliverables)
    return [(d.get("id"), new[d.get("id")]["spec_hash"]) for d in deliverables] != \
        [(d.get("id"), d.get("spec_hash")) for d in state["deliverables"]]


def _initial_state(build_id: str, customer: str, ask: str, summary: str, deliverables: List[dict],
                   job_id: str = "", story: Optional[dict] = None) -> dict:
    hashes = spec_hashes(deliverables)
    items = []
    for d in deliverables:
        unsupported = d.get("status") == "unsupported"
        h = hashes[d.get("id")]
        items.append({**{k: d.get(k, "") for k in ("id", "title", "kind", "tier", "brief", "start_from", "model",
                                                   "location", "status", "beat", "scene")},
                      "seconds": int(d.get("seconds") or 0), "input_of": d.get("input_of", ""),
                      "spec_hash": h["spec_hash"],
                      "assets": [{"label": v["label"], "language": v.get("language", ""),
                                  "status": "unsupported" if unsupported else "pending", "prompt": "", "script": "",
                                  "shots": [], "file": "", "mime": "", "model": "", "seconds": 0, "length_s": 0,
                                  "error": "", "note": "", "qa": {}, "spec_hash": h["variants"].get(v["label"], ""),
                                  "carried_over": False}
                                 for v in d.get("variants", [])]})
    return {"build_id": build_id, "job_id": job_id, "state": "queued", "error": "", "started_at": iso(),
            "updated_at": iso(), "customer": customer, "ask": ask, "summary": summary, "story": story or {},
            "deliverables": items}


def _carry_over(state: dict, previous: dict, project_dir: str) -> int:
    """Copy unchanged, ready variants (same spec hash, file still on disk) from the previous status into the new
    one. -> the number carried. A video is carried only if the image it starts from was carried too."""
    prev = {(d.get("id"), a.get("label")): a for d in previous.get("deliverables", []) if isinstance(d, dict)
            for a in d.get("assets", []) if isinstance(a, dict)}
    by_id = {d["id"]: d for d in state["deliverables"]}
    carried = set()
    for d in sorted(state["deliverables"], key=lambda x: x["kind"] == "video"):  # images before videos
        for a in d["assets"]:
            old = prev.get((d["id"], a["label"]))
            if a["status"] != "pending" or not old or old.get("status") != "ready" or \
                    not a["spec_hash"] or old.get("spec_hash") != a["spec_hash"]:
                continue
            ok = bool(old.get("prompt")) and bool(asset_path(project_dir, old))  # a chat's file: its first reply
            if ok and d["kind"] == "video" and d.get("start_from"):
                src = by_id.get(d["start_from"])
                ok = bool(src and src["assets"]) and (src["id"], src["assets"][0]["label"]) in carried
            if ok:
                a.update({k: old.get(k, a.get(k)) for k in CARRY_KEYS}, status="ready", error="", carried_over=True)
                carried.add((d["id"], a["label"]))
    return len(carried)


def _prune(project_dir: str, state: dict) -> None:
    """Delete generated files the status no longer references (replaced or dropped variants)."""
    keep = {a.get("file") for d in state["deliverables"] for a in d["assets"] if a.get("file")}
    target = folder(project_dir)
    for name in os.listdir(target):
        path = os.path.join(target, name)
        if name in keep or name == STATUS_FILE or name.startswith(".") or "__" not in name or \
                os.path.splitext(name)[1] not in MEDIA_EXTS or not os.path.isfile(path):
            continue
        with contextlib.suppress(OSError):
            os.remove(path)


# ---------------------------------------------------------------------------------------------- public API
def start(settings: Settings, *, build_id: str, project_dir: str, customer: str, ask: str, summary: str,
          deliverables: List[dict], story: Optional[dict] = None) -> str:
    """Start (or resume) generating a build's deliverables in a background thread. -> status file path.

    A new build_id, or the same build_id with a changed manifest (an edit), writes a new status: unchanged
    variants are carried over from the previous status and only the rest is directed and generated. A job still
    running on the old status is superseded (it stops at its next status update). The same build_id with the
    same manifest, or with no manifest (retry), resumes the current status. `story` (the build's story, which the
    media director writes every script from) defaults to the previous status's story."""
    path = os.path.abspath(status_path(project_dir))
    with _JOBS_LOCK:
        running = _JOBS.get(path)
        alive = bool(running and running.is_alive())
        with file_lock(path):
            state = load_status(project_dir)
            fresh = not state or state.get("build_id") != build_id or bool(
                deliverables and _spec_changed(state, deliverables))
            if alive and not fresh:
                return path
            if fresh:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                new = _initial_state(build_id, customer, ask, summary, deliverables, job_id=secrets.token_hex(8),
                                     story=story if story is not None else (state or {}).get("story"))
                if state:
                    n = _carry_over(new, state, project_dir)
                    logger.info("deliverables for %s: %d unchanged asset(s) carried over", project_dir, n)
                write_json(path, new)
                _prune(project_dir, new)
                state = new
            job_id = str(state.get("job_id") or "")
        t = threading.Thread(target=_Job(settings, project_dir, build_id, job_id).run, daemon=True,
                             name=f"deliverables-{os.path.basename(project_dir)}")
        _JOBS[path] = t
        t.start()
    return path


def retry(settings: Settings, project_dir: str) -> bool:
    """Re-run failed or interrupted assets of the current build (prompts are kept). -> True if started."""
    if is_running(project_dir):
        return False
    path = status_path(project_dir)
    with file_lock(path):
        state = load_status(project_dir)
        if not state:
            return False
        for d in state["deliverables"]:
            for a in d["assets"]:
                if a["status"] in ("failed", "running", "checking"):
                    a.update(status="pending", error="")
        state.update(state="queued", error="", updated_at=iso())
        write_json(path, state)
    start(settings, build_id=state["build_id"], project_dir=project_dir, customer=state["customer"],
          ask=state["ask"], summary=state["summary"], deliverables=[])
    return True


def cancel(project_dir: str, reason: str) -> None:
    """Stop this folder's running job at its next status update (the files it made are kept and a later build
    reuses whatever still matches)."""
    path = status_path(project_dir)
    with file_lock(path):
        state = load_status(project_dir)
        if state:
            state.update(build_id=f"cancelled-{secrets.token_hex(8)}", state="failed", error=reason[:300],
                         updated_at=iso())
            write_json(path, state)


def can_regenerate(kind: str) -> bool:
    """True for kinds whose ready asset can be generated again: media clips, texts, data outputs and chats (a
    chat's generated file is the assistant's first reply; its setup stays the media director's)."""
    return kind in manifest.REGENERABLE_KINDS


def regenerate(settings: Settings, project_dir: str, deliverable_id: str, label: str) -> bool:
    """Generate one finished clip, text, data output or chat reply again (for example one the checker flagged).
    Its prompt and script are kept, the old file is replaced when the new one is ready. -> True if started (False
    while a job runs or if not found)."""
    if is_running(project_dir):
        return False
    path = status_path(project_dir)
    with file_lock(path):
        state = load_status(project_dir)
        if not state:
            return False
        d = next((x for x in state["deliverables"] if x.get("id") == deliverable_id), None)
        a = next((x for x in (d or {}).get("assets", []) if x.get("label") == label), None)
        if not a or not can_regenerate(d.get("kind")) or a.get("status") != "ready":
            return False
        a.update(status="pending", error="", note="", qa={}, carried_over=False)
        state.update(state="queued", error="", updated_at=iso())
        write_json(path, state)
    start(settings, build_id=state["build_id"], project_dir=project_dir, customer=state["customer"],
          ask=state["ask"], summary=state["summary"], deliverables=[])
    return True


def redirect(settings: Settings, project_dir: str, kinds: Tuple[str, ...] = ("chat",)) -> int:
    """Have the media director write the prompt and script of this project's ready assets of these kinds again,
    then generate and check them anew (for example chats directed before the assistant got its context). The old
    files are replaced when the new ones are ready. -> the number of assets queued (0 while a job runs, when
    there is no status, or when nothing is ready to redo)."""
    if is_running(project_dir):
        return 0
    path = status_path(project_dir)
    with file_lock(path):
        state = load_status(project_dir)
        if not state:
            return 0
        n = 0
        for d in state["deliverables"]:
            if d.get("kind") not in kinds:
                continue
            for a in d["assets"]:
                if a.get("status") == "ready":
                    a.update(status="pending", prompt="", script="", shots=[], error="", note="", qa={},
                             carried_over=False)
                    n += 1
        if not n:
            return 0
        state.update(state="queued", error="", updated_at=iso())
        write_json(path, state)
    start(settings, build_id=state["build_id"], project_dir=project_dir, customer=state["customer"],
          ask=state["ask"], summary=state["summary"], deliverables=[])
    return n


def chat_reply(project_dir: str, asset: dict) -> str:
    """A chat asset's first reply ('' until the first turn has been played)."""
    path = asset_path(project_dir, asset) if asset.get("status") == "ready" else ""
    if not path:
        return ""
    try:
        with open(path, encoding="utf-8") as f:
            return f.read().strip()
    except OSError:
        return ""


def backfill_metrics(settings: Settings, project_dir: str, run: Optional[Callable] = None) -> int:
    """Measure the ready outputs of a saved project that have no metrics yet (builds saved before the measured
    layer existed, or whose measurement failed): one asset at a time, each written to the status file under its
    lock as soon as it is measured, skipped while a job is running on the project. Never raises.
    -> the number of outputs measured. `run(label, role, fn)` runs a model step through the resolver (the speech
    word error rate); without it that metric is reported as not measured."""
    if not getattr(settings, "output_metrics", True) or is_running(project_dir):
        return 0
    state = load_status(project_dir)
    if not state:
        return 0
    done = 0
    for d in state["deliverables"]:
        if not isinstance(d, dict) or d.get("kind") not in modality_eval.MEASURED_KINDS:
            continue
        for a in d.get("assets") or []:
            if not isinstance(a, dict) or a.get("status") != "ready":
                continue
            have = a.get("metrics") if isinstance(a.get("metrics"), dict) else {}
            if have.get("metrics") and not have.get("error"):
                continue
            path = asset_path(project_dir, a)
            if not path:
                continue
            try:
                with open(path, "rb") as fh:
                    data = fh.read()
                variant = {k: a.get(k, "") for k in ("label", "language", "script", "prompt", "shots")}
                text = media_qa.chat_text(dict(variant, reply=data.decode("utf-8", errors="replace"))) \
                    if d["kind"] == "chat" else ""
                metrics = modality_eval.measure(settings, deliverable=d, variant=variant, data=data,
                                                mime=a.get("mime", ""), text=text, run=run)
            except Exception as e:  # one output's trouble never stops the sweep
                logger.warning("could not measure %s", os.path.basename(path), exc_info=True)
                metrics = modality_eval.summarize(d["kind"], [])
                metrics["error"] = redact(str(e))[:200]
            sp = status_path(project_dir)
            with file_lock(sp):
                current = read_json(sp, None)
                if not isinstance(current, dict) or current.get("build_id") != state.get("build_id"):
                    return done  # a new build owns the file now
                for cd in current.get("deliverables") or []:
                    if cd.get("id") == d.get("id"):
                        for ca in cd.get("assets") or []:
                            if ca.get("label") == a.get("label") and ca.get("file") == a.get("file"):
                                ca["metrics"] = metrics
                write_json(sp, current)
            done += 1
    return done


def _hero(story) -> str:
    """The story's hero as one bounded line ('' if none)."""
    hero = story.get("hero") if isinstance(story, dict) else ""
    if isinstance(hero, dict):
        hero = " ".join(str(v) for v in hero.values() if isinstance(v, (str, int, float)))
    return " ".join(str(hero or "").split())[:200] if isinstance(hero, (str, int, float)) else ""


# ---------------------------------------------------------------------------------------------- the job
class _Job:
    def __init__(self, settings: Settings, project_dir: str, build_id: str, job_id: str = ""):
        self.s, self.dir, self.build_id, self.job_id = settings, project_dir, build_id, job_id
        self.path = status_path(project_dir)
        self.stop = threading.Event()
        mcp = McpKnowledgeClient(settings)
        self.resolver = ModelResolver(settings, mcp)
        self.doctor = Troubleshooter(settings, self.resolver, mcp)
        self._notes: Dict[Tuple[str, str], List[str]] = {}  # (deliverable, label) -> what happened while filming
        self._filmed: Dict[Tuple[str, str], dict] = {}      # (deliverable, label) -> shots kept across a retry
        self._lock = threading.Lock()

    # -------------------------------------------------------------- state
    def _update(self, change: Callable[[dict], None]) -> dict:
        """Apply `change` to the status file under its lock. Raises _Superseded if a newer build owns it."""
        with file_lock(self.path):
            state = read_json(self.path, None)
            if not isinstance(state, dict) or state.get("build_id") != self.build_id or \
                    str(state.get("job_id") or "") != self.job_id:
                self.stop.set()
                raise _Superseded()
            change(state)
            state["updated_at"] = iso()
            write_json(self.path, state)
            return state

    def _live(self) -> bool:
        """False once a newer build owns the status file (a lock-free read: write_json is atomic). Sets `stop`, so
        a long film ends between two shots instead of after the last one."""
        if not self.stop.is_set():
            state = read_json(self.path, None)
            if not isinstance(state, dict) or state.get("build_id") != self.build_id or \
                    str(state.get("job_id") or "") != self.job_id:
                self.stop.set()
        return not self.stop.is_set()

    def _set_asset(self, did: str, label: str, **fields) -> None:
        def change(state: dict) -> None:
            for d in state["deliverables"]:
                if d["id"] == did:
                    for a in d["assets"]:
                        if a["label"] == label:
                            a.update(fields)
        self._update(change)

    def _note(self, did: str, label: str, text: str) -> None:
        """Remember something the viewer should know about an asset being generated (written to its note)."""
        with self._lock:
            self._notes.setdefault((did, label), []).append(text)

    def _take_notes(self, did: str, label: str) -> str:
        with self._lock:
            return _join(*self._notes.pop((did, label), []))

    # -------------------------------------------------------------- run
    def run(self) -> None:
        try:
            rounds = max(0, int(self.s.media_retries))
            for n in range(rounds + 1):
                state = self._update(lambda s: s.update(state="directing" if self._needs_direction(s)
                                                        else "generating", error=""))
                if not self._needs_direction(state) or self._direct(state):
                    self._generate()
                failed = self._failed()
                if not failed or n == rounds:
                    break
                delay = RETRY_DELAYS_S[min(n, len(RETRY_DELAYS_S) - 1)]
                self._update(lambda s: s.update(state="retrying", error=f"{len(failed)} asset(s) failed; retrying "
                                                f"automatically in {delay} s (round {n + 1} of {rounds})."))
                if _pause(self.stop, delay):
                    return

                def reset(s: dict) -> None:
                    for d in s["deliverables"]:
                        for a in d["assets"]:
                            if a["status"] == "failed":
                                a.update(status="pending", error="")
                self._update(reset)
            self._update(lambda s: s.update(state="done", error="" if not self._failed() else s.get("error", "")))
        except (_Superseded, FileNotFoundError):
            logger.info("deliverables job for %s stopped: the project was rebuilt", self.dir)
        except Exception as e:  # thread boundary: record the failure where the UI can show it
            logger.exception("deliverables job failed")
            try:
                self._update(lambda s: s.update(state="failed", error=redact(str(e))[:400]))
            except (_Superseded, OSError):
                pass

    def _failed(self) -> List[Tuple[str, str]]:
        state = self._update(lambda s: None)
        return [(d["id"], a["label"]) for d in state["deliverables"] for a in d["assets"] if a["status"] == "failed"]

    @staticmethod
    def _needs_direction(state: dict) -> bool:
        return any(a["status"] == "pending" and not a["prompt"] for d in state["deliverables"] for a in d["assets"])

    def _direct(self, state: dict) -> bool:
        """Media director: a prompt and a script for every pending asset (per shot for a multi-shot video). ->
        False if it failed. When some variants of a deliverable were carried over, the director sees one of them
        so the new ones match it."""
        todo = []
        for d in state["deliverables"]:
            pending = [a for a in d["assets"] if a["status"] == "pending" and not a["prompt"]]
            if not pending:
                continue
            ref = next((a for a in d["assets"] if a["prompt"]), None)
            brief = d["brief"] + (f"\nMatch the existing variant '{ref['label']}' exactly in character, voice and "
                                  f"setting. Its prompt: {ref['prompt'][:800]}" if ref else "")
            todo.append(self._direction_spec(d, brief, pending))
        try:
            plan, _ = self.doctor.run("Media director", ROLES["director"], lambda m, loc, hint: brain.direct_media(
                self.s, m, loc, hint, customer=state["customer"], ask=state["ask"], summary=state["summary"],
                deliverables=todo, story=state.get("story")))
        except StepFailed as e:
            reason = redact(str(e))[:400]

            def failed(s: dict) -> None:
                s.update(state="failed", error=f"Media director: {reason}")
                for d in s["deliverables"]:
                    for a in d["assets"]:
                        if a["status"] == "pending" and not a["prompt"]:
                            a.update(status="failed", error=reason)
            self._update(failed)
            return False

        def apply(s: dict) -> None:
            for d in s["deliverables"]:
                for a in d["assets"]:
                    got = plan.get((d["id"], a["label"]))
                    if got and not a["prompt"]:
                        a.update(prompt=got["prompt"], script=got["script"], shots=got.get("shots") or [])
            s["state"] = "generating"
        self._update(apply)
        return True

    @staticmethod
    def _direction_spec(d: dict, brief: str, assets: List[dict]) -> dict:
        """One deliverable as the director sees it (its video length decides how many shots it writes)."""
        return ({k: d[k] for k in ("id", "title", "kind", "start_from")} | {"brief": brief}
                | {"scene": d.get("scene", ""), "seconds": int(d.get("seconds") or 0)}
                | {"variants": [{"label": a["label"], "language": a["language"]} for a in assets]})

    def _redirect_one(self, state: dict, d: dict, a: dict, finding: str) -> Optional[dict]:
        """The director writes one asset's prompt, script and shots again after a reviewer found the clip
        off-brief (wrong subject or setting). -> the new direction, or None when the director failed."""
        brief = (f"{d['brief']}\nA reviewer rejected the clip made from the previous prompt. Previous prompt: "
                 f"{a['prompt'][:600]}. Reviewer: {finding[:560]}. Write a new prompt that films exactly what this "
                 "brief asks for; the story scene is only the moment, never the subject.")
        todo = [self._direction_spec(d, brief, [a])]
        try:
            plan, _ = self.doctor.run("Media director", ROLES["director"], lambda m, loc, hint: brain.direct_media(
                self.s, m, loc, hint, customer=state["customer"], ask=state["ask"], summary=state["summary"],
                deliverables=todo, story=state.get("story")))
        except StepFailed as e:
            logger.warning("re-direct of %s/%s failed: %s", d["id"], a["label"], redact(str(e))[:200])
            return None
        got = plan.get((d["id"], a["label"]))
        if not got:
            return None
        fields = {"prompt": got["prompt"], "script": got["script"], "shots": got.get("shots") or []}
        self._set_asset(d["id"], a["label"], **fields)
        a.update(fields)
        return fields

    def _generate(self) -> None:
        state = self._update(lambda s: None)
        first, rest = [], []
        for d in state["deliverables"]:
            for a in d["assets"]:
                if a["status"] == "pending" and a["prompt"]:
                    (first if d["kind"] == "image" else rest).append((d["id"], a["label"]))
        # A chat is generated like the rest: its first turn is played (the assistant's reply is its file) and the
        # transcript is checked, so the badge says whether the assistant answers from its context.
        with ThreadPoolExecutor(max(1, self.s.media_parallel)) as ex:
            list(ex.map(self._make, first))  # images first: videos may start from them
            list(ex.map(self._make, rest))

    @staticmethod
    def _qa_deliverable(state: dict, d: dict) -> dict:
        """The deliverable as the checker sees it: with the story's hero when it plays a scene."""
        hero = _hero(state.get("story")) if d.get("scene") else ""
        return dict(d, hero=hero) if hero else d

    def _make(self, job: Tuple[str, str]) -> None:
        """Generate one asset, then (clip checker on) check it; on a failed check regenerate with the findings as
        a hint and check again. States: running -> checking -> [running -> checking -> ] ready. Works for media
        files, text deliverables and data outputs alike (a text or data output is regenerated with the findings
        in its prompt). A clip or image the reviewer found off-brief (matches_prompt failed) is not regenerated
        from the same prompt: the director writes the prompt again with the finding first (_redirect_one). A
        video's real length is read from the file (length_s) and compared with the plan (soft "length" check)."""
        if self.stop.is_set():
            return
        did, label = job
        state = self._update(lambda s: None)
        d = next(x for x in state["deliverables"] if x["id"] == did)
        a = next(x for x in d["assets"] if x["label"] == label)
        dq = self._qa_deliverable(state, d)
        self._set_asset(did, label, status="running", error="", note="", qa={})
        t0 = time.monotonic()
        first_frame, note = self._first_frame(state, d)
        try:
            data, mime, model = self._produce(d, a, first_frame, "")
        except StepFailed as e:
            self._set_asset(did, label, status="failed", error=redact(str(e))[:400],
                            note=_join(note, self._take_notes(did, label)))
            return
        note = _join(note, self._take_notes(did, label))
        length_s = self._length(d, data)
        check = bool(self.s.media_qa) and media_qa.checkable(d["kind"])
        name = self._save(did, label, data, mime, status="checking" if check else "ready", model=model,
                          seconds=round(time.monotonic() - t0, 1), length_s=length_s, note=note)
        self._discard(a.get("file", ""), name)
        if not check:
            self._measure(state, d, a, name)
            return
        qa = self._checked(dq, a, data, mime, first_frame, model, length_s)
        best = {"file": name, "model": model, "mime": mime, "qa": qa, "length_s": length_s}  # best-scoring so far
        first_summary, tried = qa["summary"], 0
        rounds = max(0, int(self.s.media_retries))
        while best["qa"]["verdict"] == "fail" and tried < rounds and not self.stop.is_set():
            tried += 1
            hint = media_qa.failed_hint(best["qa"])
            if d["kind"] in ("video", "image") and media_qa.off_brief(best["qa"]) and \
                    self._redirect_one(state, d, a, media_qa.findings(best["qa"])):
                note = _join(note, f"The checker found the {d['kind']} off-brief; the director rewrote the prompt "
                                   f"and it was made again ({tried} of {rounds}).")
                hint = ""  # the new prompt answers the finding; the old one must not travel with it
            else:
                note = _join(note, f"The checker found problems; regenerating with its findings ({tried} of {rounds}).")
            self._set_asset(did, label, status="running", qa=best["qa"], note=note)
            try:
                data2, mime2, model2 = self._produce(d, a, first_frame, hint)
            except StepFailed as e:
                note = _join(note, self._take_notes(did, label),
                             f"Regenerating after the failed check did not work: {redact(str(e))[:200]}")
                break
            note = _join(note, self._take_notes(did, label))
            length2 = self._length(d, data2)
            name2 = self._save(did, label, data2, mime2, status="checking", model=model2,
                               seconds=round(time.monotonic() - t0, 1), length_s=length2, note=note)
            qa2 = self._checked(dq, a, data2, mime2, first_frame, model2, length2)
            if qa2["verdict"] != "fail" or qa2.get("score", 0) >= best["qa"].get("score", 0):
                self._discard(best["file"], name2)
                best = {"file": name2, "model": model2, "mime": mime2, "qa": qa2, "length_s": length2}
            else:  # the new clip scored lower: keep the earlier one
                self._discard(name2, best["file"])
        qa = dict(best["qa"], regenerated=True, first_summary=first_summary) if tried else best["qa"]
        self._set_asset(did, label, status="ready", qa=qa, note=note, file=best["file"], model=best["model"],
                        mime=best["mime"], length_s=best["length_s"])
        self._measure(state, d, a, best["file"])

    def _measure(self, state: dict, d: dict, a: dict, name: str) -> None:
        """The measured layer (engine/modality_eval.py): market-standard metrics of the ready asset, stored as
        the asset's "metrics". Runs after the verdict so a slow measurement never delays a usable output, and
        never fails the asset."""
        if not getattr(self.s, "output_metrics", True) or d["kind"] not in modality_eval.MEASURED_KINDS:
            return
        state = self._update(lambda s: None)  # fresh: the director may have rewritten the prompt meanwhile
        d = next((x for x in state["deliverables"] if x["id"] == d["id"]), d)
        try:
            with open(os.path.join(folder(self.dir), name), "rb") as fh:
                data = fh.read()
            current = next((x for x in d["assets"] if x["label"] == a["label"]), a)
            variant = {k: current.get(k, "") for k in ("label", "language", "script", "prompt", "shots")}
            others = [x.get("brief", "") for x in state["deliverables"]
                      if x.get("id") != d["id"] and x.get("kind") in ("image", "video")]
            run = lambda label, role, fn: self.doctor.run(f"{label} ({d['title']})", ROLES[role],
                                                          lambda m, loc, hint: (fn(m, loc), 1.0))[0]
            metrics = modality_eval.measure(self.s, deliverable=d, variant=variant, data=data,
                                            mime=current.get("mime", ""), text=self._transcript(d, current, data),
                                            others=others, run=run)
        except Exception as e:  # measurement boundary: the asset is already ready
            logger.warning("could not measure %s", name, exc_info=True)
            metrics = modality_eval.summarize(d["kind"], [])
            metrics["error"] = redact(str(e))[:200]
        self._set_asset(d["id"], a["label"], metrics=metrics)

    @staticmethod
    def _length(d: dict, data: bytes) -> float:
        """A video's real length in seconds, read from the file (0 for the other kinds or an unreadable file)."""
        return media.mp4_duration_s(data) if d["kind"] == "video" else 0

    def _checked(self, dq: dict, a: dict, data: bytes, mime: str, first_frame: Optional[media.Media], model: str,
                 length_s: float) -> dict:
        """The reviewer's result, with the programmatic length check added for a video."""
        qa = self._check(dq, a, data, mime, first_frame, model=model, text=self._transcript(dq, a, data))
        return media_qa.with_length(qa, dq.get("seconds"), length_s) if dq["kind"] == "video" else qa

    def _produce(self, d: dict, a: dict, first_frame: Optional[media.Media], qa_hint: str) -> Tuple[bytes, str, str]:
        """One generation through the Troubleshooter. -> (data, mime, model served)."""
        (data, mime), served = self.doctor.run(f"{d['title']} ({a['label']})", d["tier"], lambda m, loc, hint: (
            self._call(d, a, m, loc, "; ".join(x for x in (qa_hint, hint) if x), first_frame), None), max_models=2)
        # quality None: the output checker reports the real quality through resolver.record_check
        return data, mime.split(";")[0].strip(), served["model"]

    def _check(self, d: dict, a: dict, data: bytes, mime: str, first_frame: Optional[media.Media],
               text: str = "", model: str = "") -> dict:
        """Clip checker through the Troubleshooter (qa role). Never raises for checker trouble: an unavailable
        checker yields verdict "skipped" with the reason, and the asset stays usable. `text` is what a chat is
        checked on (a text or data deliverable is read from `data`). A data output that breaks its JSON contract
        fails the programmatic schema check without a checker call. `model` is the model that generated the
        asset: every pass/fail verdict is reported for it (check telemetry)."""
        reference = first_frame if d["kind"] == "video" else None
        reason = media_qa.skip_reason(d, data, mime, reference, text)
        if reason:
            return dict(media_qa.skipped(reason), model="", regenerated=False)
        broken = media_qa.schema_failure(d, data, mime, text)
        if broken:
            self._record_check(d, model, broken)
            return dict(broken, model="", regenerated=False)
        variant = {k: a.get(k, "") for k in ("label", "language", "script", "prompt")}
        extra = {"text": text} if d["kind"] in media_qa.TEXT_KINDS else {}  # media calls keep their old signature
        try:
            result, served = self.doctor.run(f"Check {d['title']} ({a['label']})", ROLES["qa"], lambda m, loc, hint: (
                media_qa.check(self.s, m, loc, deliverable=d, variant=variant, data=data, mime=mime,
                               reference=reference, hint=hint, **extra), 1.0))
        except StepFailed as e:
            return dict(media_qa.skipped(f"the checker could not run: {redact(str(e))[:300]}"), model="",
                        regenerated=False)
        self._record_check(d, model, result)
        return dict(result, model=served["model"], regenerated=False)

    def _record_check(self, d: dict, model: str, qa: dict) -> None:
        """Report a pass/fail verdict for the model that generated the asset (skipped checks are not reported).
        The resolver may not offer record_check; telemetry never fails an asset."""
        verdict = (qa or {}).get("verdict")
        if verdict not in ("pass", "fail") or not model or not d.get("tier") or \
                not hasattr(self.resolver, "record_check"):
            return
        try:
            self.resolver.record_check(d["tier"], model, verdict == "pass")
        except Exception:  # telemetry boundary: log it, keep the asset
            logger.warning("could not record the output check of %s", model, exc_info=True)

    @staticmethod
    def _transcript(d: dict, a: dict, data: bytes) -> str:
        """What the checker reads for a chat: setup plus the played first reply ('' for the other kinds)."""
        if d["kind"] != "chat":
            return ""
        variant = {k: a.get(k, "") for k in ("label", "language", "script", "prompt")}
        return media_qa.chat_text(dict(variant, reply=data.decode("utf-8", errors="replace")))

    def _call(self, d: dict, a: dict, model: str, location: str, hint: str,
              first_frame: Optional[media.Media]) -> media.Media:
        retry_note = f"\n(The previous attempt failed: {hint}. Keep it brand-safe.)" if hint else ""
        prompt = a["prompt"] + retry_note
        kind = d["kind"]
        if kind == "chat":  # play the first turn: the reply is the asset
            system = a["prompt"] + (f"\n\nA reviewer rejected your previous reply: {hint}. Answer again, fully, "
                                    "from the Context above." if hint else "")
            opener = a["script"] or "Hello"
            reply = media.chat(self.s, model, location, system, [{"role": "user", "text": opener}])
            return reply.strip().encode("utf-8"), "text/markdown"
        if kind == "image":
            return media.image(self.s, model, location, prompt)
        if kind == "video":
            return self._film(d, a, model, location, retry_note, first_frame)
        if kind == "speech":
            return media.speech(self.s, model, location, a["script"] or a["prompt"],
                                style=a["prompt"] if a["script"] else "")
        if kind == "music":
            return media.music(self.s, model, location, prompt)
        if kind in manifest.DATA_KINDS:
            language = (f"\nWrite every text value in the language with BCP-47 code {a['language']}."
                        if a.get("language") else "")
            text, _ = vertex.generate(self.s, model, f"{a['prompt']}\n\n{manifest.output_contract(kind)}{language}"
                                      f"{retry_note}", location=location, json_mode=True)
            return manifest.output_bytes(manifest.parse_output(kind, text)), "application/json"
        text, _ = vertex.generate(self.s, model, prompt, location=location)
        if not text.strip():
            raise OutputError(f"{model} returned empty text")
        return text.strip().encode("utf-8"), "text/markdown"

    @staticmethod
    def _shots(d: dict, a: dict) -> List[dict]:
        """The shots of a video asset: the director's (prompt, script, seconds per shot), or one shot of the
        asset's prompt for an asset directed before shots existed (its length is then the model's default)."""
        shots = [s for s in (a.get("shots") or []) if isinstance(s, dict) and str(s.get("prompt") or "").strip()]
        if shots:
            return [{"prompt": str(s["prompt"]), "seconds": int(s.get("seconds") or 0)} for s in shots]
        return [{"prompt": a["prompt"], "seconds": 0}]

    def _film(self, d: dict, a: dict, model: str, location: str, retry_note: str,
              first_frame: Optional[media.Media]) -> media.Media:
        """A video as consecutive Veo shots (per the director's shots), each asked for its length and started
        from the last frame of the one before, joined into one file with ffmpeg. One shot is a single Veo call.
        Without ffmpeg only the first shot is filmed (the note says so). Shots already filmed by this model from
        the same prompts are reused when the Troubleshooter re-prompts after a later shot failed; the cache is
        dropped once the film is complete, so a regeneration after a failed check films everything anew."""
        key, shots = (d["id"], a["label"]), self._shots(d, a)
        if len(shots) > 1 and not media.has_ffmpeg():
            self._note(*key, f"Only shot 1 of {len(shots)} ({shots[0]['seconds'] or '?'} s of {d.get('seconds')} s) "
                             "was filmed: ffmpeg is not installed on this server, so shots cannot be joined.")
            shots = shots[:1]
        with self._lock:
            kept = self._filmed.get(key) or {}
            parts: List[bytes] = list(kept.get("parts", [])) if kept.get("model") == model else []
            prompts: List[str] = list(kept.get("prompts", [])) if kept.get("model") == model else []
        frame = first_frame
        for i, shot in enumerate(shots):
            if i and not self._live():
                break  # the project was rebuilt: the next status update ends this job
            reused = i < len(parts) and prompts[i] == shot["prompt"]
            if not reused:
                del parts[i:], prompts[i:]
                clip, _ = media.video(self.s, model, location, shot["prompt"] + retry_note, first_frame=frame,
                                      duration_s=shot["seconds"] or None)
                parts.append(clip)
                prompts.append(shot["prompt"])
                with self._lock:
                    self._filmed[key] = {"model": model, "parts": list(parts), "prompts": list(prompts)}
            if i + 1 < len(shots):
                try:
                    frame = media.last_frame(parts[i])
                except media.StitchError as e:
                    self._note(*key, f"Shot {i + 2} could not start from the end of shot {i + 1} ({e}).")
                    frame = first_frame
        with self._lock:
            self._filmed.pop(key, None)
        if len(parts) == 1:
            return parts[0], "video/mp4"
        try:
            return media.concat_videos(parts), "video/mp4"
        except media.StitchError as e:
            self._note(*key, f"Only shot 1 of {len(shots)} is shown: {e}.")
            return parts[0], "video/mp4"

    def _first_frame(self, state: dict, d: dict) -> Tuple[Optional[media.Media], str]:
        """The image a video starts from (the first ready variant of its start_from deliverable)."""
        if d["kind"] != "video" or not d.get("start_from"):
            return None, ""
        src = next((x for x in state["deliverables"] if x["id"] == d["start_from"]), None)
        for a in (src or {}).get("assets", []):
            path = asset_path(self.dir, a) if a["status"] == "ready" else ""
            if path and a.get("mime") in media.FIRST_FRAME_MIME:
                with open(path, "rb") as f:
                    return (f.read(), a["mime"]), ""
        return None, f"started without '{src['title'] if src else d['start_from']}' (that image is not available)"

    def _save(self, did: str, label: str, data: bytes, mime: str, **fields) -> str:
        """Write a generated file under a fresh unique name and point the asset at it. -> the file name. A
        superseded job deletes its own file (the unique name never collides with a newer job's file)."""
        name = f"{did}__{slugify(label)[:30]}__{secrets.token_hex(4)}{EXT.get(mime, '.bin')}"
        self._write_file(name, data)
        try:
            self._set_asset(did, label, file=name, mime=mime, **fields)
        except _Superseded:
            with contextlib.suppress(FileNotFoundError):
                os.remove(os.path.join(folder(self.dir), name))
            raise
        return name

    def _discard(self, old: str, new: str) -> None:
        """Delete a replaced file of this asset (only a plain file name inside the deliverables folder)."""
        path = asset_path(self.dir, {"file": old}) if old and old != new else ""
        if path:
            with contextlib.suppress(OSError):
                os.remove(path)

    def _write_file(self, name: str, data: bytes) -> None:
        target = folder(self.dir)
        fd, tmp = tempfile.mkstemp(dir=target, prefix=".tmp-")
        try:
            with os.fdopen(fd, "wb") as f:
                f.write(data)
            os.replace(tmp, os.path.join(target, name))
        except BaseException:
            if os.path.exists(tmp):
                os.remove(tmp)
            raise


def _join(*notes: str) -> str:
    return " ".join(n for n in notes if n)
