"""The demo story script document and its Google Doc publishing hooks."""
import os
import unittest
from unittest import mock

from engine import artifact_store, story_doc
from fakes import OfflineTestCase

XSS = "<script>alert(1)</script>"


def result(project_dir: str, story=None, deliverables=None) -> dict:
    return {"customer_name": "Acme Air", "usecase_ask": "Multilingual concierge", "slug": "acme-air",
            "build_id": "b-123", "summary": "Gemini Live on Vertex AI with Cloud Run.", "project_dir": project_dir,
            "story": story if story is not None else {}, "deliverables": deliverables or []}


STORY = {"title": "Aiko makes her connection", "logline": "A stranded traveller rebooks in Japanese.",
         "hero": "Aiko, a Cymbal Air member stuck at Narita", "challenge": "Her flight was cancelled at midnight.",
         "beats": [{"id": "b1", "title": "Stranded", "scene": "Aiko opens the app.", "feature": "Live voice"},
                   {"id": "b2", "title": "Rebooked", "scene": "The avatar rebooks her.", "feature": "Lip-sync"}],
         "payoff": "Rebooked in 90 seconds instead of 40 minutes."}


def status() -> dict:
    return {"deliverables": [
        {"id": "d2", "title": "Rebooking clip", "kind": "video", "brief": "Avatar rebooks", "beat": "b2",
         "assets": [{"label": "Japanese", "language": "ja-JP", "status": "ready", "script": "ご予約を変更しました。",
                     "prompt": "Close-up of the avatar " + "x" * 400}]},
        {"id": "d1", "title": "Opening clip", "kind": "video", "brief": "App opens", "beat": "b1",
         "assets": [{"label": "English", "language": "en-US", "status": "ready", "script": f"Hello {XSS}",
                     "prompt": "Wide shot"}]},
        {"id": "d3", "title": "Ops dashboard", "kind": "image", "brief": "Dashboard", "beat": "b9",
         "assets": [{"label": "Main", "language": "", "status": "pending", "script": "", "prompt": ""}]},
    ]}


class StoryDocTest(OfflineTestCase):
    def setUp(self) -> None:
        super().setUp()
        self.project = os.path.join(self.tmp, "out", "acme-air")
        os.makedirs(self.project)

    def test_scenes_follow_beats_with_escaped_scripts(self):
        doc = story_doc.build_story_html(result(self.project, STORY), status())
        self.assertLess(doc.index("Stranded"), doc.index("Rebooked"))
        self.assertLess(doc.index("Opening clip"), doc.index("Rebooking clip"))  # grouped under their beat
        self.assertNotIn(XSS, doc)
        self.assertIn("&lt;script&gt;alert(1)&lt;/script&gt;", doc)
        self.assertNotIn("<script", doc.lower())
        self.assertIn('<blockquote lang="ja-JP">', doc)
        self.assertIn("ご予約を変更しました。", doc)
        self.assertIn("Proves: Live voice", doc)
        self.assertNotIn("x" * 300, doc)  # the shot line is truncated
        more = doc.index("More from the demo")
        self.assertGreater(doc.index("Ops dashboard"), more)  # unknown beat b9 goes last
        self.assertIn("The payoff", doc)
        self.assertIn("Presenter talk track", doc)
        self.assertIn("Now watch as", doc)
        self.assertIn("Generated by Gemini+MCP Studio from build b-123", doc)

    def test_beat_falls_back_to_the_planned_deliverable(self):
        st = status()
        for d in st["deliverables"]:
            d.pop("beat")
        res = result(self.project, STORY, deliverables=[{"id": "d1", "beat": "b1"}, {"id": "d2", "beat": "b2"}])
        doc = story_doc.build_story_html(res, st)
        self.assertLess(doc.index("Opening clip"), doc.index("More from the demo"))
        self.assertGreater(doc.index("Ops dashboard"), doc.index("More from the demo"))

    def test_bad_language_code_is_dropped(self):
        st = status()
        st["deliverables"][0]["assets"][0]["language"] = '"><img src=x onerror=alert(1)>'
        doc = story_doc.build_story_html(result(self.project, STORY), st)
        self.assertNotIn("<img", doc)
        self.assertNotIn("onerror=alert(1)>", doc)

    def test_renders_without_story_or_status(self):
        res = result(self.project, story=None, deliverables=[
            {"id": "d1", "title": f"Clip {XSS}", "kind": "video", "brief": "b",
             "variants": [{"label": "Main", "language": "en"}]}])
        res.pop("story")
        doc = story_doc.build_story_html(res, None)
        self.assertIn("Acme Air", doc)
        self.assertIn("Gemini Live on Vertex AI", doc)  # summary as the logline
        self.assertIn("Script not written yet", doc)
        self.assertNotIn(XSS, doc)
        self.assertNotIn("More from the demo", doc)
        doc = story_doc.build_story_html({"project_dir": self.project, "story": "junk"}, {"deliverables": "junk"})
        self.assertIn("Demo story", doc)

    def test_write_is_atomic_and_idempotent(self):
        res = result(self.project, STORY)
        path = story_doc.write_story_doc(res, status())
        self.assertEqual(path, os.path.join(self.project, "deliverables", "acme-air" + story_doc.STORY_SUFFIX))
        self.assertEqual(path, story_doc.story_path(res))
        with open(path, encoding="utf-8") as f:
            self.assertEqual(f.read(), story_doc.build_story_html(res, status()))
        mtime = os.stat(path).st_mtime_ns
        with mock.patch("engine.story_doc.os.replace") as replace:
            self.assertEqual(story_doc.write_story_doc(res, status()), path)
            replace.assert_not_called()  # unchanged content: file untouched
        self.assertEqual(os.stat(path).st_mtime_ns, mtime)
        with mock.patch("engine.story_doc.os.replace", side_effect=OSError("disk full")):
            with self.assertRaises(OSError):
                story_doc.write_story_doc(res, None)
        with open(path, encoding="utf-8") as f:
            self.assertIn("ご予約を変更しました。", f.read())  # old file intact after a failed write
        self.assertEqual([n for n in os.listdir(os.path.dirname(path)) if n.endswith(".tmp")], [])

    def test_slug_cannot_escape_the_project_folder(self):
        res = result(self.project, STORY)
        res["slug"] = "../../evil"
        self.assertEqual(os.path.dirname(story_doc.story_path(res)), os.path.join(self.project, "deliverables"))

    def test_story_doc_is_never_an_unsaved_edit(self):
        from engine import deliverables as dlv, versions
        self.assertEqual(story_doc.OUTPUT_FOLDER, dlv.FOLDER)
        self.assertTrue(f"{dlv.FOLDER}/".startswith(versions.VOLATILE_PREFIXES))


class StoryDocPublishTest(unittest.TestCase):
    def test_html_converts_to_a_google_doc(self):
        conv = artifact_store.CONVERSIONS[".html"]
        self.assertEqual((conv.upload_mime, conv.google_mime, conv.url_path),
                         ("text/html", "application/vnd.google-apps.document", "document"))
        self.assertEqual(artifact_store.drive_file_url("x" + story_doc.STORY_SUFFIX, "abc_1-2"),
                         "https://docs.google.com/document/d/abc_1-2/edit")

    def test_doc_urls(self):
        self.assertEqual(artifact_store.doc_urls("abc_1-2"),
                         {"edit_url": "https://docs.google.com/document/d/abc_1-2/edit",
                          "embed_url": "https://docs.google.com/document/d/abc_1-2/preview"})

    def test_invalid_file_ids_are_rejected(self):
        for bad in ("", "../x", "a/b", "a?b=c", "a b", "javascript:alert(1)", None, 123):
            self.assertEqual(artifact_store.doc_urls(bad), {})
            self.assertEqual(artifact_store.slide_urls(bad), {})
            self.assertFalse(artifact_store.valid_drive_id(bad))


if __name__ == "__main__":
    unittest.main()
